sonar.projectKey=Sprig-front-stage
sonar.projectName=Sprig Front Stage
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**
sonar.tests=src
sonar.login=sqa_03ff96e2f9a5d251490ad0e475a7405661673742
sonar.test.inclusions=**/*.spec.ts
sonar.coverage.exclusions=**/dto/**,**/entities/**,**/*.module.ts,**/main.ts,**/node_modules/**
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.host.url=http://localhost:9000
sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e1.ruleKey=css:S4258
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.css
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S6544
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S6486
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria.e4.ruleKey=typescript:S6486
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.ts
